# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b31972f31e275ff4a0e378601c3a8c8557d94d2b657d4aa9b7cbc5a64d1fe44922e2a8c050b40f6ee6ae63972f5da98e24a0044f4cfa3254fd1db07993bf9dc1

test:
  secret_key_base: b435e6d518a7f5f8d4088a4c7ba336a6eb263423c79c1e5a20454a94020a0d0f53a1e307e0177317b44ba35d75fc9ba6bbf8b15e234eb6dc68c0b8b2026f1208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
